# Generated by Django 5.1 on 2024-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=250, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("Nom", models.CharField(max_length=50)),
                ("Prenom", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("Telephone", models.IntegerField()),
                ("Pays", models.CharField(blank=True, max_length=50, null=True)),
                ("ville", models.CharField(blank=True, max_length=50, null=True)),
                ("cond_ut", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
